### ISSUE TITLE
Salesforce Marketing Cloud Developer Tools (Google Chrome Extension)

### ISSUE THREAD

**Issue by mslabina** [sfmcdg/awesome-salesforce-marketingcloud#1]
I developed an extension for Google Chrome developer tools that is designed to help Marketing Cloud developers, admins and users by adding information to the interface that isn't present, helping export data in structured way (JSON), etc. This extension is available free of charge and published under MIT license. In my opinion this could be very valuable for others.

I'm also open to feature requests, suggestions and contributions and always keen on implementing them.

- [Extension in the Chrome Webstore](https://chrome.google.com/webstore/detail/salesforce-marketing-clou/bkmmmgaljahinmpijhdggabkdngpadbn)
- [Product website](https://markus.codes/sfmc-chrome-devtools)
- [GitHub repository](https://github.com/mslabina/sfmc-chrome-devtools)

**Comment by eliotharper** [comment]
Hi Markus, thanks for the suggestion. I use your extension regularly and it's very helpful. We should definitely list this resource.

**Comment by mslabina** [comment]
Hi Eliot,

I'm glad you like my extension! If you have any ideas on how to further improve it please feel free to [raise an issue on github](https://github.com/mslabina/sfmc-chrome-devtools/issues/new).

Cheers,
Markus

**Comment by mattcam** [comment]
Thanks @mslabina for the awesome suggestion and @eliotharper for review.
