### ISSUE TITLE
Marketing Cloud Connect

### ISSUE THREAD

**Issue by unaiskomath** [sfmcdg/awesome-salesforce-marketingcloud#4]
http://help.marketingcloud.com/en/documentation/integrated_products__crm_and_web_analytic_solutions/marketing_cloud_connector_v5/ 

Marketing CLoud COnnect Integration Steps - http://help.marketingcloud.com/en/documentation/integrated_products__crm_and_web_analytic_solutions/marketing_cloud_connector_v5/connecting_the_clouds/

**Comment by mattcam** [comment]
thanks @unaiskomath for suggestions
